server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: system
              uri: http://localhost:8082
              predicates:
                - Path=/api/system/**,/api/auth/**
              filters:
                - StripPrefix=0
            - id: payment
              uri: http://localhost:8081
              predicates:
                - Path=/api/payments/**,/api/loan/**,/api/contracts/**
            - id: message
              uri: http://localhost:8083
              predicates:
                - Path=/api/messages/**
            - id: report
              uri: http://localhost:8084
              predicates:
                - Path=/api/reports/**

security:
  jwt:
    secret: nMc+2ISSIUcy4YSPSbCOSSdse7LZyB/kzkjnfhZVXtc=
    expiration: 8640000
