-- 创建订单表
CREATE TABLE IF NOT EXISTS cls_order (
    ORDER_ID VARCHAR(32) PRIMARY KEY COMMENT '订单编号',
    CONTR_NO VARCHAR(32) COMMENT '合同编号',
    BILL_NO VARCHAR(32) COMMENT '账单编号',
    ORDER_TYPE VARCHAR(32) COMMENT '订单类型',
    ORDER_AMT DECIMAL(15,2) COMMENT '订单金额',
    CARD_NO VARCHAR(32) COMMENT '银行卡号',
    BANK_CODE VARCHAR(32) COMMENT '银行编码',
    EXT_ORDER_ID VARCHAR(32) COMMENT '外部订单编号',
    ORDER_STATUS VARCHAR(4) COMMENT '订单状态',
    FAIL_REASON VARCHAR(500) COMMENT '失败原因',
    NEED_AUDIT VARCHAR(1) DEFAULT 'N' COMMENT '是否需要审核：Y-需要，N-不需要审核状态',
    AUDIT_STATUS VARCHAR(4) DEFAULT 'N' COMMENT '审核状态：N-无需审核，U-待审核，A-已通过，R-已拒绝',
    PRODUCT_ID VARCHAR(128) COMMENT '产品编号',
    WITHDRAW_MODE VARCHAR(4) COMMENT '放款方式：L-放款到客户，M-结算到商户',
    PAY_TIME DATETIME COMMENT '支付时间',
    CREATE_TIME DATETIME COMMENT '创建时间',
    UPDATE_TIME DATETIME COMMENT '更新时间',
    INDEX idx_ext_order_id (EXT_ORDER_ID),
    INDEX idx_contr_no (CONTR_NO),
    INDEX idx_bill_no (BILL_NO),
    INDEX idx_order_status (ORDER_STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单表';

-- 创建贷款登记表
CREATE TABLE IF NOT EXISTS cls_loan_reg (
    LOAN_REG_ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '贷款编号',
    CUST_ID VARCHAR(32) NOT NULL COMMENT '客户编号',
    CONTR_NO VARCHAR(32) COMMENT '合同编号',
    BILL_NO VARCHAR(32) COMMENT '账单编号',
    LENDING_AMT DECIMAL(15,2) COMMENT '贷款金额',
    LOAN_PRIN DECIMAL(15,2) NOT NULL COMMENT '贷款本金',
    TXN_FEE_AMT DECIMAL(15,2) DEFAULT 0.00 COMMENT '交易手续费金额',
    LOAN_ACTION VARCHAR(32) NOT NULL COMMENT '贷款行为',
    AUDIT_RESULT VARCHAR(40) DEFAULT 'U' COMMENT '审核结果',
    LOAN_REG_STATUS VARCHAR(32) DEFAULT 'U' COMMENT '贷款状态',
    EXT_BIZ_ORDER_ID VARCHAR(32) DEFAULT 'SYSTEM' COMMENT '外部订单编号',
    APLLY_TIME DATETIME NOT NULL COMMENT '申请时间',
    ORDER_ID VARCHAR(32) COMMENT '订单编号',
    JPA_VERSION BIGINT DEFAULT 0 COMMENT '版本控制字段',
    INDEX idx_cust_id (CUST_ID),
    INDEX idx_contr_no (CONTR_NO),
    INDEX idx_bill_no (BILL_NO),
    INDEX idx_ext_biz_order_id (EXT_BIZ_ORDER_ID),
    INDEX idx_audit_result (AUDIT_RESULT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='贷款登记表';

-- 创建还款计划表
CREATE TABLE IF NOT EXISTS cls_repay_plan (
    PLAN_ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '计划编号',
    BILL_NO VARCHAR(32) NOT NULL COMMENT '账单编号',
    CONTR_NO VARCHAR(32) COMMENT '合同编号',
    CUST_ID VARCHAR(32) COMMENT '客户编号',
    TERM_NO INT COMMENT '期数',
    DUE_DATE DATETIME COMMENT '到期时间',
    PRIN_AMT DECIMAL(15,2) COMMENT '本金',
    INTEREST_AMT DECIMAL(15,2) COMMENT '利息',
    FEE_AMT DECIMAL(15,2) COMMENT '手续费',
    TOTAL_AMT DECIMAL(15,2) COMMENT '合计金额',
    PAID_PRIN DECIMAL(15,2) COMMENT '已还本金',
    PAID_INTEREST DECIMAL(15,2) COMMENT '已还利息',
    PAID_FEE DECIMAL(15,2) COMMENT '已还手续费',
    REMAIN_AMT DECIMAL(15,2) COMMENT '剩余金额',
    STATUS VARCHAR(4) COMMENT '状态',
    OVERDUE_DAYS INT COMMENT '逾期天数',
    CREATE_TIME DATETIME COMMENT '创建时间',
    UPDATE_TIME DATETIME COMMENT '更新时间',
    INDEX idx_bill_no (BILL_NO),
    INDEX idx_contr_no (CONTR_NO),
    INDEX idx_status (STATUS),
    INDEX idx_due_date (DUE_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='还款计划表';

-- 创建还款记录表
CREATE TABLE IF NOT EXISTS cls_repay_record (
    RECORD_ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '记录编号',
    BILL_NO VARCHAR(32) COMMENT '账单编号',
    CONTR_NO VARCHAR(32) COMMENT '合同编号',
    CUST_ID VARCHAR(32) COMMENT '客户编号',
    ORDER_ID VARCHAR(32) COMMENT '订单编号',
    REPAY_AMT DECIMAL(15,2) COMMENT '还款金额',
    PRIN_AMT DECIMAL(15,2) COMMENT '本金',
    INTEREST_AMT DECIMAL(15,2) COMMENT '利息',
    FEE_AMT DECIMAL(15,2) COMMENT '手续费',
    OVERPAY_AMT DECIMAL(15,2) COMMENT '超收金额',
    REPAY_TYPE VARCHAR(32) COMMENT '还款方式',
    PAY_STATUS VARCHAR(4) COMMENT '支付状态',
    FAIL_REASON VARCHAR(500) COMMENT '失败原因',
    PAY_TIME DATETIME COMMENT '支付时间',
    ACCOUNT_TIME DATETIME COMMENT '入账时间',
    CREATE_TIME DATETIME COMMENT '创建时间',
    REMARK VARCHAR(500) COMMENT '备注',
    INDEX idx_bill_no (BILL_NO),
    INDEX idx_order_id (ORDER_ID),
    INDEX idx_pay_status (PAY_STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='还款记录表';

-- 创建对账异常表
CREATE TABLE IF NOT EXISTS recon_exception (
    EXCEPTION_ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '异常编号',
    ORDER_ID VARCHAR(32) COMMENT '订单编号',
    BILL_NO VARCHAR(32) COMMENT '账单编号',
    CUST_ID VARCHAR(32) COMMENT '客户编号',
    EXCEPTION_TYPE VARCHAR(32) NOT NULL COMMENT '异常类型',
    PAY_AMT DECIMAL(15,2) COMMENT '支付金额',
    CORE_AMT DECIMAL(15,2) COMMENT '核心金额',
    DIFF_AMT DECIMAL(15,2) COMMENT '差异金额',
    STATUS VARCHAR(4) COMMENT '状态',
    HANDLE_METHOD VARCHAR(32) COMMENT '处理方式',
    HANDLE_RESULT VARCHAR(500) COMMENT '处理结果',
    CREATE_TIME DATETIME COMMENT '创建时间',
    HANDLE_TIME DATETIME COMMENT '处理时间',
    REMARK VARCHAR(1000) COMMENT '备注',
    INDEX idx_order_id (ORDER_ID),
    INDEX idx_exception_type (EXCEPTION_TYPE),
    INDEX idx_status (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='对账异常表';

-- 创建客户银行卡表
CREATE TABLE IF NOT EXISTS cust_card (
    CARD_NO VARCHAR(32) PRIMARY KEY COMMENT '银行卡号',
    BANK_CODE VARCHAR(32) NOT NULL COMMENT '银行编码',
    PAY_DIRECTION VARCHAR(32) NOT NULL COMMENT '支付方向',
    CUST_ID VARCHAR(32) NOT NULL COMMENT '客户编号',
    INDEX idx_cust_id (CUST_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='客户银行卡表';

-- 借据期供信息表
CREATE TABLE IF NOT EXISTS cls_term (
    ORG VARCHAR(12) COMMENT '机构号',
    TERM_ID BIGINT NOT NULL COMMENT '期供ID',
    CUST_ID VARCHAR(32) NOT NULL COMMENT '客户ID',
    CONTR_NO VARCHAR(32) NOT NULL COMMENT '合同号',
    BILL_NO VARCHAR(32) NOT NULL COMMENT '借款号',
    PRODUCT_CD VARCHAR(8) NOT NULL COMMENT '产品代码',
    PRODUCT_SUB_CD VARCHAR(24) NOT NULL COMMENT '产品子代码',
    TERM_TYPE CHAR(1) NOT NULL COMMENT '期供类型',
    TERM_NO INT NOT NULL COMMENT '期数',
    TERM_STATUS CHAR(1) NOT NULL COMMENT '期供状态',
    PMT_DUE_DATE DATE NOT NULL COMMENT '应还日期',
    DUE_BAL DECIMAL(15,2) NOT NULL COMMENT '应还余额',
    SCHD_PRIN DECIMAL(15,2) NOT NULL COMMENT '应还本金',
    SCHD_INT DECIMAL(15,2) NOT NULL COMMENT '应还利息',
    LOAN_REMAIN_PRIN DECIMAL(15,2) NOT NULL COMMENT '贷款剩余本金',
    CTD_PRIN DECIMAL(15,2) NOT NULL COMMENT '当前本金',
    PAST_PRIN DECIMAL(15,2) NOT NULL COMMENT '过往本金',
    CTD_INT DECIMAL(15,2) NOT NULL COMMENT '当前利息',
    CTD_PEN DECIMAL(15,2) NOT NULL COMMENT '当前罚息',
    CTD_COMP DECIMAL(15,2) NOT NULL COMMENT '当前违约金',
    ACRU_INT DECIMAL(16,8) NOT NULL COMMENT '累计利息',
    ACRU_COMP DECIMAL(16,8) NOT NULL COMMENT '累计违约金',
    PAID_PRIN DECIMAL(15,2) NOT NULL COMMENT '已还本金',
    PAID_INT DECIMAL(15,2) NOT NULL COMMENT '已还利息',
    PAID_PEN DECIMAL(15,2) NOT NULL COMMENT '已还罚息',
    PAID_COMP DECIMAL(15,2) NOT NULL COMMENT '已还违约金',
    PAID_AMT DECIMAL(15,2) NOT NULL COMMENT '已还金额',
    WAV_INT DECIMAL(15,2) NOT NULL COMMENT '待还利息',
    WAV_PEN DECIMAL(15,2) NOT NULL COMMENT '待还罚息',
    WAV_COMP DECIMAL(15,2) NOT NULL COMMENT '待还违约金',
    WAV_AMT DECIMAL(15,2) NOT NULL COMMENT '待还金额',
    TOT_INT DECIMAL(15,2) NOT NULL COMMENT '总计利息',
    TOT_PEN DECIMAL(15,2) NOT NULL COMMENT '总计罚息',
    TOT_COMP DECIMAL(15,2) NOT NULL COMMENT '总计违约金',
    SETUP_DATE DATE NOT NULL COMMENT '创建日期',
    PAID_OUT_DATE DATE COMMENT '结息日期',
    INT_RATE DECIMAL(12,8) NOT NULL COMMENT '利率',
    PEN_RATE DECIMAL(12,8) NOT NULL COMMENT '罚息率',
    CREATE_TIME DATETIME NOT NULL COMMENT '创建时间',
    CREATE_USER VARCHAR(32) NOT NULL COMMENT '创建用户',
    UPDATE_TIME DATETIME NOT NULL COMMENT '更新时间',
    UPDATE_USER VARCHAR(32) NOT NULL COMMENT '更新用户',
    JPA_VERSION BIGINT NOT NULL COMMENT 'JPA版本',
    PRIMARY KEY (TERM_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='借据期供信息表';

-- 借据期供费用表
CREATE TABLE IF NOT EXISTS cls_term_fee (
    ORG VARCHAR(12) NOT NULL COMMENT '机构号',
    TERM_FEE_ID BIGINT NOT NULL COMMENT '期供费用ID',
    TERM_ID BIGINT NOT NULL COMMENT '期供ID',
    CUST_ID VARCHAR(32) NOT NULL COMMENT '客户ID',
    CONTR_NO VARCHAR(32) NOT NULL COMMENT '合同号',
    BILL_NO VARCHAR(32) NOT NULL COMMENT '借款号',
    TERM_NO INT NOT NULL COMMENT '期数',
    LOAN_FEE_CD VARCHAR(32) NOT NULL COMMENT '贷款费用代码',
    LOAN_FEE_NAME VARCHAR(64) NOT NULL COMMENT '贷款费用名称',
    SCHD_FEE_AMT DECIMAL(15,2) NOT NULL COMMENT '应缴费用金额',
    CTD_FEE_AMT DECIMAL(15,2) NOT NULL COMMENT '当前费用金额',
    PAID_FEE_AMT DECIMAL(15,2) NOT NULL COMMENT '已缴费用金额',
    WAV_FEE_AMT DECIMAL(15,2) NOT NULL COMMENT '待缴费用金额',
    CREATE_TIME DATETIME NOT NULL COMMENT '创建时间',
    CREATE_USER VARCHAR(32) NOT NULL COMMENT '创建用户',
    UPDATE_TIME DATETIME NOT NULL COMMENT '更新时间',
    UPDATE_USER VARCHAR(32) NOT NULL COMMENT '更新用户',
    JPA_VERSION BIGINT NOT NULL COMMENT 'JPA版本',
    PRIMARY KEY (TERM_FEE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='借据期供费用表';

-- 交易流水表
CREATE TABLE IF NOT EXISTS cls_txn (
    ORG VARCHAR(12) NOT NULL COMMENT '机构号',
    TXN_SEQ BIGINT NOT NULL COMMENT '交易序列号',
    CUST_ID VARCHAR(32) NOT NULL COMMENT '客户ID',
    CONTR_NO VARCHAR(32) NOT NULL COMMENT '合同号',
    BILL_NO VARCHAR(32) NOT NULL COMMENT '借款号',
    PRODUCT_CD VARCHAR(8) NOT NULL COMMENT '产品代码',
    TERM_NO INT NOT NULL COMMENT '期数',
    TXN_GROUP VARCHAR(16) NOT NULL COMMENT '交易组别',
    TXN_CODE CHAR(4) NOT NULL COMMENT '交易代码',
    TXN_DESC VARCHAR(80) NOT NULL COMMENT '交易描述',
    TXN_STMT_DESC VARCHAR(80) NOT NULL COMMENT '交易摘要描述',
    DB_CR_IND CHAR(1) NOT NULL COMMENT '借贷标志',
    POST_AMT DECIMAL(15,2) NOT NULL COMMENT '过账金额',
    POST_DATE DATE NOT NULL COMMENT '过账日期',
    TXN_AMT DECIMAL(15,2) NOT NULL COMMENT '交易金额',
    TXN_DATE DATE NOT NULL COMMENT '交易日期',
    TXN_TIME DATETIME NOT NULL COMMENT '交易时间',
    BLOCK_CODE VARCHAR(27) COMMENT '交易区块码',
    ORDER_ID BIGINT COMMENT '交易订单ID',
    TXN_ADJ_ID BIGINT COMMENT '交易调整ID',
    BANK_FLOW_NO BIGINT COMMENT '银行流水号',
    FUND_COMPEN_ID BIGINT COMMENT '基金补偿ID',
    AGENT_COMPEN_ID BIGINT COMMENT '代理补偿ID',
    CREATE_TIME DATETIME NOT NULL COMMENT '创建时间',
    CREATE_USER VARCHAR(32) NOT NULL COMMENT '创建用户',
    UPDATE_TIME DATETIME NOT NULL COMMENT '更新时间',
    UPDATE_USER VARCHAR(32) NOT NULL COMMENT '更新用户',
    JPA_VERSION BIGINT NOT NULL COMMENT 'JPA版本',
    PRIMARY KEY (TXN_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='交易流水表';

-- 借据定义表
CREATE TABLE IF NOT EXISTS cls_loan_def (
    LOAN_REG_ID BIGINT NOT NULL COMMENT '贷款登记表ID',
    INTEREST_RATE DECIMAL(10,6) NOT NULL COMMENT '年利率',
    INTEREST_RATE_TYPE VARCHAR(32) COMMENT '利率类型',
    FLOAT_RATE DECIMAL(10,6) COMMENT '浮动利率',
    PRIMARY KEY (LOAN_REG_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='借据定义表';

-- 合同信息表
CREATE TABLE IF NOT EXISTS CLS_CONTRACT
(	CONTR_NO VARCHAR(64) NOT NULL COMMENT '合同号',
	CUST_ID varchar(32) NOT NULL comment '客户ID',
	PRODUCT_ID varchar(32) comment '产品id',
	SIGN_AMT decimal(10,2) comment '签署金额',
    CONTR_STATUS varchar(32) comment '合同状态',
    PRIMARY KEY (CONTR_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT = '借据定义表';
-- 客户信息表
CREATE TABLE IF NOT EXISTS CUST_INFO
(	
	CUST_ID varchar(32) NOT NULL comment '客户ID',
    CUST_NAME varchar(32) NOT NULL comment '客户姓名',
	CERT_NO varchar(32) NOT NULL comment '证件号码',
	CERT_TYPE varchar(32) NOT NULL comment '证件类型' DEFAULT '01',
    mobile varchar(32) NOT NULL comment '手机号码',
    PRIMARY KEY (CUST_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT = '客户信息表';

-- 借据事件表
CREATE TABLE IF NOT EXISTS CLS_LOAN_EVENT
(
	LOAN_EVENT_ID bigint NOT NULL COMMENT '唯一ID',
	CUST_ID varchar(32) NOT NULL comment '客户ID',
	CONTR_NO varchar(32) comment '合同号',
	BILL_NO varchar(32) comment '票据号',
	TERM_NO int comment '期数',
	LOAN_EVENT_TYPE varchar(40) NOT NULL comment '借据事件类型',
	MEMO varchar(400) NOT NULL comment '备注' DEFAULT '',
	SETUP_TIME datetime NOT NULL comment '操作时间'  DEFAULT CURRENT_TIMESTAMP,
	OPT_USER_NAME varchar(40) comment '操作用户姓名',
	CREATE_TIME datetime NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP,
	CREATE_USER varchar(32) NOT NULL COMMENT '创建用户' DEFAULT 'SYSTEM',
	JPA_VERSION bigint NOT NULL COMMENT 'JPA版本号默认0' DEFAULT 0,
	PRIMARY KEY (LOAN_EVENT_ID)
) COMMENT = '借据事件表-审计日志';

-- 产品信息表
CREATE TABLE IF NOT EXISTS PRODUCT
(
	PRODUCT_ID VARCHAR(128) NOT NULL COMMENT '唯一ID',
	PRODUCT_NAME varchar(256) NOT NULL comment '产品名称',
	WITHDRAW_MODE varchar(32) comment '取现方式',
	REPAY_METHOD varchar(32) comment '还款方式',
	description varchar(512) comment '描述',
	PRIMARY KEY (PRODUCT_ID)
) COMMENT = '产品信息表';
