-- 插入测试数据

-- 0. 确保必要的表存在（如果 V2 中没有创建这些表）
CREATE TABLE IF NOT EXISTS cls_contract (
    CONTR_NO VARCHAR(32) PRIMARY KEY COMMENT '合同号',
    CUST_ID VARCHAR(32) NOT NULL COMMENT '客户ID',
    PRODUCT_ID VARCHAR(32) COMMENT '产品ID',
    SIGN_AMT DECIMAL(10,2) COMMENT '签署金额',
    CONTR_STATUS VARCHAR(32) COMMENT '合同状态'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合同表';

CREATE TABLE IF NOT EXISTS cust_info (
    CUST_ID VARCHAR(32) PRIMARY KEY COMMENT '客户ID',
    CUST_NAME VARCHAR(32) NOT NULL COMMENT '客户姓名',
    CERT_NO VARCHAR(32) NOT NULL COMMENT '证件号码',
    CERT_TYPE VARCHAR(32) NOT NULL DEFAULT '01' COMMENT '证件类型',
    MOBILE VARCHAR(32) NOT NULL COMMENT '手机号码'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='客户信息表';

CREATE TABLE IF NOT EXISTS cls_loan_event (
    LOAN_EVENT_ID BIGINT PRIMARY KEY COMMENT '事件ID',
    CUST_ID VARCHAR(32) NOT NULL COMMENT '客户ID',
    CONTR_NO VARCHAR(32) COMMENT '合同号',
    BILL_NO VARCHAR(32) COMMENT '票据号',
    TERM_NO INT COMMENT '期数',
    LOAN_EVENT_TYPE VARCHAR(40) NOT NULL COMMENT '借据事件类型',
    MEMO VARCHAR(400) NOT NULL DEFAULT '' COMMENT '备注',
    SETUP_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
    OPT_USER_NAME VARCHAR(40) COMMENT '操作用户姓名',
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    CREATE_USER VARCHAR(32) NOT NULL DEFAULT 'SYSTEM' COMMENT '创建用户',
    JPA_VERSION BIGINT NOT NULL DEFAULT 0 COMMENT 'JPA版本号'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='借据事件表-审计日志';


-- 1. 插入测试客户信息
INSERT INTO cust_info (cust_id, cust_name, cert_no, cert_type, mobile) VALUES
('CUST001', '张三', '110101199001011234', 'ID_CARD', '13800138000'),
('CUST002', '李四', '110101199002022345', 'ID_CARD', '13800138001');

-- 2. 插入测试合同
INSERT INTO cls_contract (contr_no, cust_id, product_id, sign_amt, contr_status) VALUES
('CONTR20260101001', 'CUST001', 'PROD001', 100000.00, 'A'),
('CONTR20260101002', 'CUST002', 'PROD001', 50000.00, 'A');

-- 3. 插入测试银行卡
INSERT INTO cust_card (card_no, bank_code, pay_direction, cust_id) VALUES
('6222021234567890', 'ICBC', 'RECEIVE', 'CUST001'),
('6222021234567891', 'ICBC', 'RECEIVE', 'CUST002');

SELECT '测试数据初始化完成' AS result;
